# Generated by Django 5.0.2 on 2024-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_tag_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='account.tag'),
        ),
    ]
